// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT_C373uHQ1HUJG9G55QB4cn7Rhu4Vahw',
    appId: '1:1046112362504:web:aa48a70e15ee5bf0dd31bd',
    messagingSenderId: '1046112362504',
    projectId: 'bullcare',
    authDomain: 'bullcare.firebaseapp.com',
    storageBucket: 'bullcare.firebasestorage.app',
    measurementId: 'G-J1T0G6LEME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeE0pMXIAsnaMyhP7QcDma_4v1cT2vvL0',
    appId: '1:1046112362504:android:55d0b838e1bdb3fddd31bd',
    messagingSenderId: '1046112362504',
    projectId: 'bullcare',
    storageBucket: 'bullcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0aIJFxs5JUqXfDY3TXl27k-x8UsAfxro',
    appId: '1:1046112362504:ios:22ee6910fe847ecddd31bd',
    messagingSenderId: '1046112362504',
    projectId: 'bullcare',
    storageBucket: 'bullcare.firebasestorage.app',
    iosBundleId: 'com.example.bullcareBib',
  );
}
